// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using UnityEditor;
using System;

namespace Hiker.GUIManager.Editor {
    //public class GUIManager_PackageUtilities: UnityEditor.Editor {

    //    public static void ImportProjectResourcesMenu() { }
    //}
    public class GUIManager_PackageUtilities
    {

        public static void ImportProjectResourcesMenu() { }
    }
}