// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace Hiker.GUIManager.Editor {
    public static class Hiker_EditorUtility {

        public static string packageFullPath => default( string );
    }
}