// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using UnityEngine;
using System;
using Hiker;

namespace Hiker {
    public class DynamicResolutionQuad: UnityEngine.MonoBehaviour {

        internal UnityEngine.Camera cam3D;

        internal UnityEngine.Camera mainCamera;

        internal int targetFPS;

        internal float minScale;

        internal float maxScale;

        internal float currentScale;

        internal bool isBicubicUpscale;

        internal static Hiker.DynamicResolutionQuad instance;

        public bool IsCpuBotneck => default( bool );
        public void SetCamera( UnityEngine.Camera cam ) { }
    }
}