// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace Hiker {
    public static class HikerLog {

        public static void LogEditorOnly( string msg, string chanel, string htmlColor ) { }
        public static void LogDebugOnly( string msg, string chanel, string htmlColor ) { }
        public static void WarnEditorOnly( string msg, string chanel, string htmlColor ) { }
        public static void WarnDebugOnly( string msg, string chanel, string htmlColor ) { }
    }
}