// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Collections;
using System.Threading.Tasks;
using Hiker;

namespace Hiker {
    public class UnityMainThreadDispatcher: UnityEngine.MonoBehaviour {

        public void Update() { }
        public void Enqueue( System.Collections.IEnumerator action ) { }
        public void Enqueue( System.Action action ) { }
        public System.Threading.Tasks.Task EnqueueAsync( System.Action action ) {
            return default( System.Threading.Tasks.Task );
        }
        public static bool Exists() {
            return default( bool );
        }
        public static Hiker.UnityMainThreadDispatcher Instance() {
            return default( Hiker.UnityMainThreadDispatcher );
        }
    }
}