// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using Hiker.Util;
using System;

namespace Hiker.Util {
    public static class ArrayPool<T> {

        public static T[] Claim( int minimumLength ) {
            return default( T[] );
        }
        public static void Release( ref T[] array ) { }
    }
}