// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Collections.Generic;
using Hiker.Util;
using System;

namespace Hiker.Util {
    public static class ListPool<T> {

        public static System.Collections.Generic.List<T> Claim() {
            return default( System.Collections.Generic.List<T> );
        }
        public static System.Collections.Generic.List<T> Claim( int capacity ) {
            return default( System.Collections.Generic.List<T> );
        }
        public static void Warmup( int count, int size ) { }
        public static void Release( List<T> list ) { }
        public static void Clear() { }
        public static int GetSize() {
            return default( int );
        }
    }
}