// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Collections.Generic;
using Hiker.Util;
using System;
using UnityEngine;
using System.Collections;

namespace Hiker.Util {
    public class ObjectPoolManager: UnityEngine.MonoBehaviour {

        internal System.Collections.Generic.List<Hiker.Util.Pool> poolList;

        internal static Hiker.Util.ObjectPoolManager instance;

        internal System.Collections.Generic.List<Hiker.Util.ObjectPoolManager.AutoUnspawnObj> autoUnSpawnObjects;

        internal System.Collections.Generic.Dictionary<UnityEngine.GameObject, int> autoUnspawnIndexes;

        public void PreCachePool( UnityEngine.GameObject prefab, int count ) { }
        public System.Collections.IEnumerator PreCachePool( string resourcePath, int count ) {
            return default( System.Collections.IEnumerator );
        }
        public Hiker.Util.Pool GetPool( string path ) {
            return default( Hiker.Util.Pool );
        }
        public static UnityEngine.Transform Spawn( UnityEngine.Transform objT ) {
            return default( UnityEngine.Transform );
        }
        public static UnityEngine.Transform Spawn( UnityEngine.Transform objT, UnityEngine.Vector3 pos, UnityEngine.Quaternion rot, UnityEngine.Transform parent ) {
            return default( UnityEngine.Transform );
        }
        public static UnityEngine.GameObject SpawnResourcesBundle( string path ) {
            return default( UnityEngine.GameObject );
        }
        public static UnityEngine.GameObject Spawn( UnityEngine.GameObject obj ) {
            return default( UnityEngine.GameObject );
        }
        public static UnityEngine.GameObject Spawn( UnityEngine.GameObject obj, UnityEngine.Vector3 pos, UnityEngine.Quaternion rot, UnityEngine.Transform parent ) {
            return default( UnityEngine.GameObject );
        }
        public static UnityEngine.GameObject Spawn( UnityEngine.GameObject obj, UnityEngine.Transform parent ) {
            return default( UnityEngine.GameObject );
        }
        public static UnityEngine.GameObject Spawn( string path ) {
            return default( UnityEngine.GameObject );
        }
        public static UnityEngine.GameObject Spawn( string path, UnityEngine.Vector3 pos, UnityEngine.Quaternion rot, UnityEngine.Transform parent ) {
            return default( UnityEngine.GameObject );
        }
        public UnityEngine.GameObject _Spawn( string path, UnityEngine.Vector3 pos, UnityEngine.Quaternion rot, UnityEngine.Transform parent ) {
            return default( UnityEngine.GameObject );
        }
        public UnityEngine.GameObject _Spawn( UnityEngine.GameObject obj, UnityEngine.Vector3 pos, UnityEngine.Quaternion rot, UnityEngine.Transform parent ) {
            return default( UnityEngine.GameObject );
        }
        public UnityEngine.GameObject _Spawn( UnityEngine.GameObject obj, UnityEngine.Transform parent ) {
            return default( UnityEngine.GameObject );
        }
        public static UnityEngine.GameObject SpawnDieBloodStain( string path, UnityEngine.Vector3 pos, UnityEngine.Quaternion rot, float dis, float duration ) {
            return default( UnityEngine.GameObject );
        }
        public static UnityEngine.GameObject SpawnAutoDestroy( string path, UnityEngine.Vector3 pos, UnityEngine.Quaternion rot, float duration ) {
            return default( UnityEngine.GameObject );
        }
        public static UnityEngine.GameObject SpawnAutoDestroy( UnityEngine.GameObject obj, UnityEngine.Vector3 pos, UnityEngine.Quaternion rot, float duration ) {
            return default( UnityEngine.GameObject );
        }
        public static UnityEngine.GameObject SpawnAutoDestroy( string path, float duration ) {
            return default( UnityEngine.GameObject );
        }
        public static UnityEngine.GameObject SpawnAutoUnSpawn( UnityEngine.GameObject obj, float duration, UnityEngine.Transform trans ) {
            return default( UnityEngine.GameObject );
        }
        public void AutoUnSpawn( UnityEngine.GameObject obj, float duration ) { }
        public static void Unspawn( UnityEngine.Transform objT ) { }
        public static void Unspawn( UnityEngine.GameObject obj ) { }
        public void _Unspawn( UnityEngine.GameObject obj, bool onDestroy ) { }
        public static int New( UnityEngine.Transform objT, int count ) {
            return default( int );
        }
        public static int New( UnityEngine.GameObject obj, int count ) {
            return default( int );
        }
        public int _New( UnityEngine.GameObject obj, int count ) {
            return default( int );
        }
        public int _New( string path, int count ) {
            return default( int );
        }
        public int _NewOrExpandPool( UnityEngine.GameObject obj, string path, int count ) {
            return default( int );
        }
        public static void Init() { }
        public static void ClearAll() { }
        public static UnityEngine.Transform GetOPMTransform() {
            return default( UnityEngine.Transform );
        }
        public struct AutoUnspawnObj {

        public UnityEngine.GameObject Go { get; set; }
        public float Time { get; set; }
        }
    }
}