// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using Hiker.Util;
using System;

namespace Hiker.Util {
    public static class ObjectPool<T>    where T : class, IAstarPooledObject {

        public static T Claim() {
            return default( T );
        }
        public static void Warmup( int count ) { }
        public static void Release( T obj ) { }
        public static void Clear() { }
        public static int GetSize() {
            return default( int );
        }
    }
}