// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using UnityEngine;
using System.Collections.Generic;

namespace Hiker.Util {
    public class Pool {

        internal string prefabName;

        internal UnityEngine.GameObject prefab;

        internal System.Collections.Generic.List<UnityEngine.GameObject> inactiveList;

        internal System.Collections.Generic.List<UnityEngine.GameObject> activeList;

        internal int cap;

        public UnityEngine.GameObject Spawn( UnityEngine.Vector3 pos, UnityEngine.Quaternion rot, UnityEngine.Transform parent ) {
            return default( UnityEngine.GameObject );
        }
        public UnityEngine.GameObject Spawn( UnityEngine.Transform parent ) {
            return default( UnityEngine.GameObject );
        }
        public bool Unspawn( UnityEngine.GameObject obj, bool onDestroy ) {
            return default( bool );
        }
        public void UnspawnAll() { }
        public void MatchObjectCount( int count ) { }
        public int GetTotalObjectCount() {
            return default( int );
        }
        public void Clear() { }
    }
}