// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Collections.Generic;
using Hiker.Util;
using System;

namespace Hiker.Util {
    public static class StackPool<T> {

        public static System.Collections.Generic.Stack<T> Claim() {
            return default( System.Collections.Generic.Stack<T> );
        }
        public static void Warmup( int count ) { }
        public static void Release( Stack<T> stack ) { }
        public static void Clear() { }
        public static int GetSize() {
            return default( int );
        }
    }
}