// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using UnityEngine;
using System.Collections.Generic;
using Hiker.GUI;
using System;
using Hiker;

namespace Hiker.GUI {
    public class GUIManager: UnityEngine.MonoBehaviour {

        internal UnityEngine.Transform ScreenContainer;

        internal UnityEngine.Transform PopupManagerTransform;

        internal UnityEngine.Transform TopCanvasTransform;

        internal System.Collections.Generic.Dictionary<string, Hiker.GUI.ScreenBase> screens;

        public static Hiker.GUI.GUIManager Instance => default( Hiker.GUI.GUIManager );
        public string LastScreen { get; set; }
        public string CurrentScreen { get; set; }
        public void ClearScreen() { }
        public Hiker.GUI.ScreenBase SetScreen( string screen_name, System.Action onScreenActive ) {
            return default( Hiker.GUI.ScreenBase );
        }
        public Hiker.GUI.ScreenBase GetCurrentScreen() {
            return default( Hiker.GUI.ScreenBase );
        }
    }
}