// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using UnityEngine;

namespace Hiker.GUI {
    public static class HikerGUIExtensions {

        public static void DestroyChildren( this UnityEngine.Transform t ) { }
    }
}