// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using Hiker.GUI;
using System;

namespace Hiker.GUI {
    public class HikerHaptic: UnityEngine.MonoBehaviour {

        internal static Hiker.GUI.LogsLevel LogLevel;

        internal static Hiker.GUI.HikerHaptic instance;

        internal bool HapticEnable;

        public static bool IsHapticSupport => default( bool );
        public void PlayTapEffect() { }
        public void PlayHeavyImpact() { }
        public void Initialize() { }
        public void LoadPrefSetting() { }
        public void SavePrefSetting() { }
    }
}