// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using UnityEngine.Events;

namespace Hiker.GUI {
    public class PopupBase: UnityEngine.MonoBehaviour {

        internal bool isModal;

        internal bool addToBackStack;

        internal bool hideIsDestroy;

        internal float timeDelayDestroy;

        internal bool noneBlockControl;

        internal bool nonCachePref;

        internal UnityEngine.Animator appearAnimator;

        //internal TweenAlpha appearTweenAlpha;

        internal UnityEngine.GameObject myGO;

        internal bool isClosed;

        internal UnityEngine.Events.UnityEvent onPopupClosed;

        protected virtual void Awake() { }
        protected virtual void OnEnable() { }
        protected virtual void OnDisable() { }
        public void MakePopupToTop() { }
        protected virtual void OnCleanUp() { }
        public virtual void OnBackBtnClick() { }
        public virtual void OnCloseBtnClick() { }
        protected virtual void Hide() { }
    }
}