// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Collections.Generic;
using Hiker.GUI;
using System;
using UnityEngine;
using Hiker;

namespace Hiker.GUI {
    public class PopupManager: UnityEngine.MonoBehaviour {

        internal System.Collections.Generic.List<Hiker.GUI.PopupBase> activePopups;

        public static Hiker.GUI.PopupManager instance => default( Hiker.GUI.PopupManager );
        public bool DisablePopupQueue { get; set; }
        public bool IsHavePopupBlockControl() {
            return default( bool );
        }
        public void ClearAll() { }
        public bool HaveBackStackPopup() {
            return default( bool );
        }
        public void OnBackBtnClick() { }
        public void OnShowPopup( Hiker.GUI.PopupBase popup ) { }
        public void OnHidePopup( Hiker.GUI.PopupBase popup ) { }
        public void OnCreatePopup( Hiker.GUI.PopupBase popup ) { }
        public UnityEngine.GameObject PreloadPopup( string popupName ) {
            return default( UnityEngine.GameObject );
        }
        public UnityEngine.GameObject GetPopup( string popupName, bool useDefaultPos, UnityEngine.Vector3 pos, bool isMultiInstance ) {
            return default( UnityEngine.GameObject );
        }
        public UnityEngine.GameObject GetPopupInQueue( string popupName, bool useDefaultPos, UnityEngine.Vector3 pos, bool isMultiInstance ) {
            return default( UnityEngine.GameObject );
        }
    }
}