// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace Hiker.GUI {
    public class ScreenBase: UnityEngine.MonoBehaviour {

        public bool DestroyWhenDeactive { get; set; }
        public virtual void OnActive() { }
        public virtual void OnDeactive() { }
        protected virtual void OnRectTransformDimensionsChange() { }
        public virtual bool OnBackBtnClick() {
            return default( bool );
        }
        public virtual bool IsShouldShowBanner() {
            return default( bool );
        }
    }
}