// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using Hiker.GUI;
using UnityEngine;
using System;
using System.Collections;

namespace Hiker.GUI {
    public class SoundManager: UnityEngine.MonoBehaviour {

        internal static Hiker.GUI.SoundManager instance;

        internal UnityEngine.AudioSource musicSource;

        internal UnityEngine.AudioClip mainClip;

        internal UnityEngine.AudioClip battleClip;

        internal bool MusicEnable;

        internal bool SoundEnable;

        public void LoadSoundAndMusicSetting() { }
        public void SaveSoundAndMusicSetting() { }
        public void MuteAudio() { }
        public void UnmuteAudio() { }
        public void ApplySoundAndMusicSetting() { }
        public void StartMainMusic() { }
        public void StartFadeOutMusic() { }
        public void StartBattleMusic() { }
        public System.Collections.IEnumerator FadeInBattle( float FadeTime ) {
            return default( System.Collections.IEnumerator );
        }
        public System.Collections.IEnumerator FadeOutMusic( float FadeTime ) {
            return default( System.Collections.IEnumerator );
        }
        public System.Collections.IEnumerator FadeInMain( float FadeTime ) {
            return default( System.Collections.IEnumerator );
        }
        public UnityEngine.AudioClip PlaySound( string path ) {
            return default( UnityEngine.AudioClip );
        }
        public void PlaySound( UnityEngine.AudioClip clip, float vol ) { }
    }
}