// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using UnityEngine;
using System;

namespace Hiker.GUI {
    public class SpriteCollection: UnityEngine.ScriptableObject {

        internal UnityEngine.Sprite[] sprites;

        internal Hiker.GUI.SpriteCollection.SpriteVariantName[] variantNames;

        public UnityEngine.Sprite GetSprite( string spriteName ) {
            return default( UnityEngine.Sprite );
        }
        public struct SpriteVariantName {

        internal string Var;

        internal string Org;

        }
    }
}