// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using UnityEngine.UI;
using UnityEngine;
using System;

namespace Hiker.UI {
    public class ColorSlider: UnityEngine.MonoBehaviour {

        internal UnityEngine.UI.Image sliderFill;

        internal UnityEngine.Color colorLoading;

        internal UnityEngine.Color colorFull;

        internal bool lerpColor;

    }
}