// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using UnityEditor;
using System;

namespace Hiker.UI {
    public class HikerAspectRatioFitterEditor { //: UnityEditor.UI.SelfControllerEditor

        protected virtual void OnEnable() { }
        //public override void OnInspectorGUI() { }
    }
}