// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using UnityEngine.UI;
using System;
using UnityEngine;

namespace Hiker.UI {
    public class HikerSliderByRectMask: UnityEngine.MonoBehaviour {

        internal UnityEngine.UI.Slider.Direction direction;

        public float value { get; set; }
        public UnityEngine.Vector4 GetPaddingByValue( float val, float width, float height ) {
            return default( UnityEngine.Vector4 );
        }
    }
}