// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using UnityEngine.UI;
using UnityEngine.EventSystems;
using UnityEngine;
using System;
using Hiker.UI;
using Hiker;

namespace Hiker.UI {
    public class HikerScrollRect: UnityEngine.EventSystems.UIBehaviour, UnityEngine.UI.ILayoutGroup, UnityEngine.EventSystems.IBeginDragHandler, UnityEngine.EventSystems.IInitializePotentialDragHandler, UnityEngine.EventSystems.IDragHandler, UnityEngine.EventSystems.IEndDragHandler, UnityEngine.UI.ICanvasElement, UnityEngine.EventSystems.IScrollHandler, UnityEngine.UI.ILayoutElement {

        internal UnityEngine.Vector2 m_ContentStartPosition;

        internal UnityEngine.Bounds m_ContentBounds;

        public UnityEngine.RectTransform content { get; set; }
        public bool horizontal { get; set; }
        public bool vertical { get; set; }
        public Hiker.UI.HikerScrollRect.MovementType movementType { get; set; }
        public float elasticity { get; set; }
        public bool inertia { get; set; }
        public float decelerationRate { get; set; }
        public float scrollSensitivity { get; set; }
        public UnityEngine.RectTransform viewport { get; set; }
        public UnityEngine.UI.Scrollbar horizontalScrollbar { get; set; }
        public UnityEngine.UI.Scrollbar verticalScrollbar { get; set; }
        public Hiker.UI.HikerScrollRect.ScrollbarVisibility horizontalScrollbarVisibility { get; set; }
        public Hiker.UI.HikerScrollRect.ScrollbarVisibility verticalScrollbarVisibility { get; set; }
        public float horizontalScrollbarSpacing { get; set; }
        public float verticalScrollbarSpacing { get; set; }
        public Hiker.UI.HikerScrollRect.ScrollRectEvent onValueChanged { get; set; }
        internal UnityEngine.RectTransform viewRect => default( UnityEngine.RectTransform );
        public UnityEngine.Vector2 velocity { get; set; }
        public bool IsDragging => default( bool );
        internal UnityEngine.RectTransform rectTransform => default( UnityEngine.RectTransform );
        public UnityEngine.Vector2 normalizedPosition { get; set; }
        public float horizontalNormalizedPosition { get; set; }
        public float verticalNormalizedPosition { get; set; }
        public bool hNeedScrollContent => default( bool );
        public bool vNeedScrollContent => default( bool );
        internal bool hScrollingNeeded => default( bool );
        internal bool vScrollingNeeded => default( bool );
        public virtual float minWidth => default( float );
        public virtual float preferredWidth => default( float );
        public virtual float flexibleWidth => default( float );
        public virtual float minHeight => default( float );
        public virtual float preferredHeight => default( float );
        public virtual float flexibleHeight => default( float );
        public virtual int layoutPriority => default( int );
        public virtual void Rebuild( UnityEngine.UI.CanvasUpdate executing ) { }
        public virtual void LayoutComplete() { }
        public virtual void GraphicUpdateComplete() { }
        protected override void OnEnable() { }
        protected override void OnDisable() { }
        public override bool IsActive() {
            return default( bool );
        }
        public virtual void StopMovement() { }
        public virtual void OnScroll( UnityEngine.EventSystems.PointerEventData data ) { }
        public virtual void OnInitializePotentialDrag( UnityEngine.EventSystems.PointerEventData eventData ) { }
        public virtual void OnBeginDrag( UnityEngine.EventSystems.PointerEventData eventData ) { }
        public virtual void OnEndDrag( UnityEngine.EventSystems.PointerEventData eventData ) { }
        public virtual void OnDrag( UnityEngine.EventSystems.PointerEventData eventData ) { }
        protected virtual void SetContentAnchoredPosition( UnityEngine.Vector2 position ) { }
        protected virtual void LateUpdate() { }
        protected void UpdatePrevData() { }
        protected virtual void SetNormalizedPosition( float value, int axis ) { }
        public void CenterOnRectTransform( UnityEngine.RectTransform rectTrans, bool clamp ) { }
        public void CenterOnRectTransform( UnityEngine.RectTransform rectTran, int axis, bool clamp ) { }
        public float GetNormalizePosition( UnityEngine.RectTransform rectTran, int axis ) {
            return default( float );
        }
        protected override void OnRectTransformDimensionsChange() { }
        public virtual void CalculateLayoutInputHorizontal() { }
        public virtual void CalculateLayoutInputVertical() { }
        public virtual void SetLayoutHorizontal() { }
        public virtual void SetLayoutVertical() { }
        protected void UpdateBounds() { }
        internal static void AdjustBounds( ref UnityEngine.Bounds viewBounds, ref UnityEngine.Vector2 contentPivot, ref UnityEngine.Vector3 contentSize, ref UnityEngine.Vector3 contentPos ) { }
        public UnityEngine.Bounds GetBounds() {
            return default( UnityEngine.Bounds );
        }
        internal static UnityEngine.Bounds InternalGetBounds( UnityEngine.Vector3[] corners, ref UnityEngine.Matrix4x4 viewWorldToLocalMatrix ) {
            return default( UnityEngine.Bounds );
        }
        internal static UnityEngine.Vector2 InternalCalculateOffset( ref UnityEngine.Bounds viewBounds, ref UnityEngine.Bounds contentBounds, bool horizontal, bool vertical, Hiker.UI.HikerScrollRect.MovementType movementType, ref UnityEngine.Vector2 delta ) {
            return default( UnityEngine.Vector2 );
        }
        protected void SetDirty() { }
        protected void SetDirtyCaching() { }
        public bool SetExcludeTransform( UnityEngine.RectTransform trans ) {
            return default( bool );
        }
        //protected override void OnValidate() { }
        //UnityEngine.Transform @UnityEngine.UI.ICanvasElement.get_transform() {
        //    return default( UnityEngine.Transform );
        //}
        public enum MovementType {
            Unrestricted = 0,
            Elastic = 1,
            Clamped = 2,
        }
        public enum ScrollbarVisibility {
            Permanent = 0,
            AutoHide = 1,
            AutoHideAndExpandViewport = 2,
        }
        public class ScrollRectEvent: UnityEngine.Events.UnityEvent<UnityEngine.Vector2> {

        }
    }
}