// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using UnityEngine.UI;
using Hiker.UI;
using System;
using Hiker;

namespace Hiker.UI {
    public class HikerAspectFitter: UnityEngine.EventSystems.UIBehaviour, UnityEngine.UI.ILayoutSelfController {

        public Hiker.UI.HikerAspectFitter.AspectMode aspectMode { get; set; }
        public float aspectRatio { get; set; }
        internal UnityEngine.RectTransform rectTransform => default( UnityEngine.RectTransform );
        protected override void OnEnable() { }
        protected override void OnDisable() { }
        protected virtual void Update() { }
        protected override void OnRectTransformDimensionsChange() { }
        public virtual void SetLayoutHorizontal() { }
        public virtual void SetLayoutVertical() { }
        protected void SetDirty() { }
        //protected override void OnValidate() { }
        public enum ActiveCondition {
            Always = 0,
            LargerRatio = 1,
            SmallerRatio = 2,
        }
        public enum AspectMode {
            None = 0,
            WidthControlsHeight = 1,
            HeightControlsWidth = 2,
            FitInParent = 3,
            EnvelopeParent = 4,
        }
    }
}