// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using UnityEditor;
using System;

namespace Hiker.UI {
    public class HikerScrollRectEditor { //: UnityEditor.Editor

        protected virtual void OnEnable() { }
        protected virtual void OnDisable() { }
        //public override void OnInspectorGUI() { }
    }
}