// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using UnityEngine.UI;
using Hiker.UI;
using System;
using UnityEngine;
using Hiker;

namespace Hiker.UI {
    public class HikerGridLayoutGroup: UnityEngine.UI.LayoutGroup {

        internal Hiker.UI.HikerGridLayoutGroup.Corner m_StartCorner;

        internal Hiker.UI.HikerGridLayoutGroup.Axis m_StartAxis;

        internal UnityEngine.Vector2 m_CellSize;

        internal UnityEngine.Vector2 m_Spacing;

        internal Hiker.UI.HikerGridLayoutGroup.Constraint m_Constraint;

        internal int m_ConstraintCount;

        public Hiker.UI.HikerGridLayoutGroup.Corner startCorner { get; set; }
        public Hiker.UI.HikerGridLayoutGroup.Axis startAxis { get; set; }
        public UnityEngine.Vector2 cellSize { get; set; }
        public UnityEngine.Vector2 spacing { get; set; }
        public Hiker.UI.HikerGridLayoutGroup.Constraint constraint { get; set; }
        public int constraintCount { get; set; }
        //protected override void OnValidate() { }
        public override void CalculateLayoutInputHorizontal() { }
        public override void CalculateLayoutInputVertical() { }
        public override void SetLayoutHorizontal() { }
        public override void SetLayoutVertical() { }
        public enum Corner {
            UpperLeft = 0,
            UpperRight = 1,
            LowerLeft = 2,
            LowerRight = 3,
        }
        public enum Axis {
            Horizontal = 0,
            Vertical = 1,
        }
        public enum Constraint {
            Flexible = 0,
            FixedColumnCount = 1,
            FixedRowCount = 2,
        }
    }
}