// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using UnityEngine;
using UnityEngine.UI;

namespace Hiker.UI {
    public class SelectableSpriteSwap: UnityEngine.MonoBehaviour {

        internal UnityEngine.Sprite DisableSprite;

        internal UnityEngine.Sprite NormalSprite;

        internal UnityEngine.UI.Image Target;

    }
}