// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using UnityEngine.EventSystems;
using UnityEngine;

namespace Hiker.UI {
    public class SelectableSound: UnityEngine.MonoBehaviour, UnityEngine.EventSystems.IPointerClickHandler {

        internal UnityEngine.AudioClip sound;

        void @UnityEngine.EventSystems.IPointerClickHandler.OnPointerClick( UnityEngine.EventSystems.PointerEventData eventData ) { }
    }
}