// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using UnityEngine.EventSystems;

namespace Hiker.UI {
    public class SelectableHaptic: UnityEngine.MonoBehaviour, UnityEngine.EventSystems.IPointerClickHandler {

        void @UnityEngine.EventSystems.IPointerClickHandler.OnPointerClick( UnityEngine.EventSystems.PointerEventData eventData ) { }
    }
}