// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using UnityEngine.UI;
using System;

namespace Hiker.UI {
    public class SyncTextSize: UnityEngine.MonoBehaviour {

        internal UnityEngine.UI.Text[] texts;

        internal float timeDelaySync;

        internal float cycleResizeOnUpdate;

        public void RecalculateSize() { }
    }
}