// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using UnityEngine.UI;

namespace Hiker.UI {
    public class SyncImageWhenEnable: UnityEngine.MonoBehaviour {

        internal UnityEngine.UI.Image target;

    }
}