// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using UnityEngine;
using System;

namespace Hiker.UI {
    public class ToggleAnimation: UnityEngine.MonoBehaviour {

        internal UnityEngine.Animator iconAnimator;

        public void OnTogleValueChanged( bool isActive ) { }
    }
}