// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace Hiker.UI {
    public class ToggleTween: UnityEngine.MonoBehaviour {

        //internal UITweener[] tweeners;

        public void OnTogleValueChanged( bool isActive ) { }
    }
}