// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using UnityEngine;
using System;

namespace Hiker.UI {
    public class ToggleFollow: UnityEngine.MonoBehaviour {

        internal UnityEngine.GameObject follower;

        internal float delay;

        internal UnityEngine.Vector2 anchorOffset;

        public void UpdateFollower() { }
    }
}