// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using UnityEngine;
using System;

namespace Hiker.Utils {
    public class GameObjectStateSync: UnityEngine.MonoBehaviour {

        internal UnityEngine.GameObject[] Targets;

        internal bool isOpposite;

    }
}