// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using UnityEngine;
using System;
public class HikerScrollRectDirectionNotice: UnityEngine.MonoBehaviour {

    internal UnityEngine.GameObject upNotice;

    internal UnityEngine.GameObject downNotice;

    internal UnityEngine.GameObject leftNotice;

    internal UnityEngine.GameObject rightNotice;

    internal float horizontalThresold;

    internal float verticalThresold;

}